"""Create Folium HTML map of clean RRU networks and sampled R-tree filtered points.

Layers:
- rru_with_intersection_clean.geojson (fishbone/intersection network)
- rru_backbone_clean.geojson (backbone-only network)
- 20 m metric buffer around rru_with_intersection_clean for R-tree threshold context
- sampled points retained by R-tree with MAX_DIST_METERS = 20 m

Output:
- deliverables/maps/rru_clean_networks_rtree_points_20m.html
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import folium
import geopandas as gpd
import polars as pl
from folium.plugins import Fullscreen, MeasureControl, MiniMap, MarkerCluster

from configs import intersections
from src.rru.paths import (
    RRU_BACKBONE_CLEAN_GEOJSON,
    RRU_WITH_INTERSECTION_CLEAN_GEOJSON,
    require_path,
)

OUTPUT_DIR = PROJECT_ROOT / "deliverables" / "maps"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RTREE_CANDIDATES = PROJECT_ROOT / "data" / "interim" / "gps_rru_candidates.parquet"
OUT_HTML = OUTPUT_DIR / "rru_clean_networks_rtree_points_20m.html"
BUFFER_M = 20.0
METRIC_CRS = "EPSG:32749"  # UTM zone 49S, suitable for Yogyakarta
WGS84 = "EPSG:4326"
DEFAULT_SAMPLE_POINTS = 1000
RANDOM_SEED = 42


def _clean_for_geojson(gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    """Convert non-JSON-friendly columns to strings for Folium GeoJson."""
    out = gdf.copy()
    for col in out.columns:
        if col == out.geometry.name:
            continue
        out[col] = out[col].apply(
            lambda value: json.dumps(value, ensure_ascii=False)
            if isinstance(value, (list, dict, tuple))
            else value
        )
    return out


def _ensure_wgs84(gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    if gdf.crs is None:
        gdf = gdf.set_crs(WGS84)
    return gdf.to_crs(WGS84)


def _load_sampled_rtree_points(sample_points: int, seed: int) -> tuple[pl.DataFrame, int, int]:
    """Load deterministic sampled R-tree candidate points from the 20 m candidate file."""
    require_path(RTREE_CANDIDATES, "R-tree 20 m candidate points")
    lf = pl.scan_parquet(RTREE_CANDIDATES)
    counts = lf.select(
        pl.len().alias("total_filtered_points"),
        pl.col("maid").n_unique().alias("total_filtered_maids"),
    ).collect()
    total_points = int(counts["total_filtered_points"][0])
    total_maids = int(counts["total_filtered_maids"][0])

    # The candidate parquet was generated by src/rru/preprocessing/interim/rtree.py
    # with configs.MAX_DIST_METERS = 20.0, then singleton MAIDs were dropped.
    points = (
        lf.select(
            "maid",
            "latitude",
            "longitude",
            "timestamp",
            pl.col("candidate_dists").list.min().alias("min_dist_m"),
            pl.col("candidate_edge_keys").list.len().alias("n_candidate_edges"),
        )
        .collect()
    )

    n_sample = min(sample_points, total_points)
    if n_sample < total_points:
        points = points.sample(n=n_sample, seed=seed, shuffle=True)
    return points, total_points, total_maids


def _dist_color(min_dist_m: float) -> str:
    if min_dist_m <= 5:
        return "#00e676"  # green
    if min_dist_m <= 10:
        return "#ffeb3b"  # yellow
    if min_dist_m <= 15:
        return "#ff9800"  # orange
    return "#ff1744"      # red


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sample-points", type=int, default=DEFAULT_SAMPLE_POINTS)
    parser.add_argument("--seed", type=int, default=RANDOM_SEED)
    args = parser.parse_args()

    with_intersections = _ensure_wgs84(
        gpd.read_file(require_path(RRU_WITH_INTERSECTION_CLEAN_GEOJSON, "QGIS-clean RRU with intersections"))
    )
    backbone = _ensure_wgs84(
        gpd.read_file(require_path(RRU_BACKBONE_CLEAN_GEOJSON, "QGIS-clean RRU backbone"))
    )

    roads_m = with_intersections.to_crs(METRIC_CRS)
    buffer_gdf = gpd.GeoDataFrame(
        {
            "name": ["Buffer R-tree 20 m dari rru_with_intersection_clean"],
            "buffer_m": [BUFFER_M],
        },
        geometry=[roads_m.geometry.buffer(BUFFER_M).union_all()],
        crs=METRIC_CRS,
    ).to_crs(WGS84)

    sampled_points, total_filtered_points, total_filtered_maids = _load_sampled_rtree_points(
        args.sample_points,
        args.seed,
    )

    bounds = with_intersections.total_bounds  # minx, miny, maxx, maxy
    center_lat = (bounds[1] + bounds[3]) / 2
    center_lon = (bounds[0] + bounds[2]) / 2

    m = folium.Map(
        location=[center_lat, center_lon],
        zoom_start=14,
        tiles="CartoDB positron",
        control_scale=True,
        prefer_canvas=True,
    )
    folium.TileLayer("OpenStreetMap", name="OpenStreetMap", control=True).add_to(m)
    folium.TileLayer("CartoDB positron", name="CartoDB Positron", control=True).add_to(m)
    folium.TileLayer("CartoDB dark_matter", name="CartoDB Dark", control=True).add_to(m)
    folium.TileLayer("Esri.WorldImagery", name="Esri Satellite", control=True).add_to(m)

    folium.GeoJson(
        buffer_gdf.to_json(),
        name="Buffer R-tree 20 m",
        style_function=lambda _feature: {
            "fillColor": "#ff7800",
            "color": "#ff7800",
            "weight": 1,
            "fillOpacity": 0.16,
            "opacity": 0.65,
        },
        tooltip=folium.GeoJsonTooltip(fields=["name", "buffer_m"], aliases=["Layer", "Buffer (m)"]),
    ).add_to(m)

    with_clean = _clean_for_geojson(with_intersections)
    backbone_clean = _clean_for_geojson(backbone)
    tooltip_fields_with = [c for c in ["name", "highway", "length", "oneway", "network_role"] if c in with_clean.columns]
    tooltip_fields_backbone = [c for c in ["name", "highway", "length", "oneway", "network_role"] if c in backbone_clean.columns]

    folium.GeoJson(
        with_clean.to_json(),
        name="rru_with_intersection_clean — jaringan + lengan simpang",
        style_function=lambda _feature: {
            "color": "#1e88e5",
            "weight": 3,
            "opacity": 0.82,
        },
        tooltip=folium.GeoJsonTooltip(fields=tooltip_fields_with) if tooltip_fields_with else None,
    ).add_to(m)

    folium.GeoJson(
        backbone_clean.to_json(),
        name="rru_backbone_clean — backbone",
        style_function=lambda _feature: {
            "color": "#ffb300",
            "weight": 6,
            "opacity": 0.98,
        },
        tooltip=folium.GeoJsonTooltip(fields=tooltip_fields_backbone) if tooltip_fields_backbone else None,
    ).add_to(m)

    point_layer = folium.FeatureGroup(
        name=f"Sampel titik lolos R-tree 20 m ({sampled_points.height:,} dari {total_filtered_points:,})",
        show=True,
    )
    cluster = MarkerCluster(name="Cluster titik R-tree 20 m", control=False).add_to(point_layer)
    for idx, row in enumerate(sampled_points.iter_rows(named=True), start=1):
        min_dist = float(row["min_dist_m"])
        popup = (
            f"<b>Titik sampel #{idx}</b><br>"
            f"min_dist: {min_dist:.2f} m<br>"
            f"candidate edges: {int(row['n_candidate_edges'])}<br>"
            f"timestamp: {int(row['timestamp'])}<br>"
            f"maid prefix: {html.escape(str(row['maid'])[:8])}…"
        )
        folium.CircleMarker(
            location=[float(row["latitude"]), float(row["longitude"])],
            radius=3.2,
            color=_dist_color(min_dist),
            weight=1,
            fill=True,
            fill_color=_dist_color(min_dist),
            fill_opacity=0.82,
            tooltip=f"min_dist={min_dist:.2f} m",
            popup=popup,
        ).add_to(cluster)
    point_layer.add_to(m)

    for name, coord in intersections.items():
        folium.CircleMarker(
            location=[coord["latitude"], coord["longitude"]],
            radius=6,
            color="#6a1b9a",
            fill=True,
            fill_color="#ab47bc",
            fill_opacity=0.96,
            tooltip=name.title(),
            popup=f"<b>{name.title()}</b><br>lat={coord['latitude']}<br>lon={coord['longitude']}",
        ).add_to(m)

    legend_html = f"""
    <div style="position: fixed; bottom: 34px; left: 34px; z-index: 9999;
                background: rgba(255,255,255,0.94); color: #222; padding: 11px 13px;
                border: 1px solid #777; border-radius: 7px; font-size: 13px;
                box-shadow: 0 2px 6px rgba(0,0,0,0.25);">
      <b>RRU clean network + R-tree 20 m</b><br>
      <span style="color:#1e88e5; font-weight:bold;">━━</span> rru_with_intersection_clean<br>
      <span style="color:#ffb300; font-weight:bold;">━━</span> rru_backbone_clean<br>
      <span style="color:#ff7800;">▰</span> buffer 20 m<br>
      <span style="color:#00e676;">●</span> titik ≤5 m &nbsp;
      <span style="color:#ffeb3b;">●</span> ≤10 m &nbsp;
      <span style="color:#ff9800;">●</span> ≤15 m &nbsp;
      <span style="color:#ff1744;">●</span> ≤20 m<br>
      Total lolos R-tree 20 m: {total_filtered_points:,} ping / {total_filtered_maids:,} MAID<br>
      Sampel ditampilkan: {sampled_points.height:,} titik
    </div>
    """
    m.get_root().html.add_child(folium.Element(legend_html))

    folium.LayerControl(collapsed=False).add_to(m)
    Fullscreen(position="topleft").add_to(m)
    MiniMap(toggle_display=True, minimized=True).add_to(m)
    MeasureControl(position="topleft", primary_length_unit="meters").add_to(m)
    m.fit_bounds([[bounds[1], bounds[0]], [bounds[3], bounds[2]]])

    m.save(OUT_HTML)
    print(f"Saved: {OUT_HTML}")
    print(f"Filtered points source: {RTREE_CANDIDATES}")
    print(f"Displayed sample points: {sampled_points.height:,}")
    print(f"Total filtered points: {total_filtered_points:,}")
    print(f"Total filtered MAIDs: {total_filtered_maids:,}")


if __name__ == "__main__":
    main()
